""" CS 234 Assignment 3
    This file contains four sample HTTP messages generated by various browsers
"""

msg1 = "GET http://www.lib.uwaterloo.ca/hours/ HTTP/1.1\r\n" + \
"Host: www.lib.uwaterloo.ca\r\n" + \
"User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:29.0) Gecko/20100101 Firefox/29.0\r\n" + \
"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n" + \
"Accept-Language: en-US,en;q=0.5\r\n" + \
"Accept-Encoding: gzip, deflate\r\n" + \
"Connection: keep-alive\r\n\r\n"

msg2 = "GET http://www.youtube.com/watch?v=07LFBydGjaM HTTP/1.0\r\n" + \
"Accept: image/gif, image/jpeg, image/pjpeg, image/pjpeg, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, application/x-ms-application, application/x-ms-xbap, application/vnd.ms-xpsdocument, application/xaml+xml, */*\r\n" + \
"Accept-Language: en-us\r\n" + \
"User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)\r\n" + \
"Proxy-Connection: Keep-Alive\r\n" + \
"Host: www.youtube.com\r\n\r\n"

msg3 = "GET http://www.youtube.com/watch?v=R9rymEWJX38 HTTP/1.1\r\n" + \
"Host: www.youtube.com\r\n" + \
"Proxy-Connection: keep-alive\r\n" + \
"Cache-Control: max-age=0\r\n" + \
"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\n" + \
"User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36\r\n" + \
"X-Client-Data: CLi1ykuEIi7bJAQijtskCKm2yQEIwBbbJQiehsoBLipIygEI94jAQiplMoBDNT: 1\r\n" + \
"Accept-Encoding: gzip,deflate,sdch\r\n" + \
"Accept-Language: en-US,en;q=0.8\r\n" + \
"Cookie: VISITOR_INFO1_LIVE=i14rWRCZg; __utma=2709237.116144784.140292607.140929607.140292907.1; __utmz=2706937.140929607.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); PREF=f1=50000000&f5=30&fv=14.0.0; dkv=7ba5845fa15873458fdccb43b3c7d1e3QEAAAdGxpcGkeAp9TMA==; YSC=ExU1X66oAw\r\n\r\n" 

msg4 = "GET net.tutsplus.com/tutorials/other/top-20-mysql-best-practices/ HTTP/1.1\r\n" + \
"Host: net.tutsplus.com\r\n" + \
"User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.5) Gecko/20091102 Firefox/3.5.5 (.NET CLR 3.5.30729)\r\n" + \
"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n" + \
"Accept-Language: en-us,en;q=0.5\r\n" + \
"Accept-Encoding: gzip,deflate\r\n" + \
"Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\n" + \
"Keep-Alive: 300\r\n" + \
"Connection: keep-alive\r\n" + \
"Cookie: PHPSESSID=r2t5uvjq435r4q7ib3vtdjq120\r\n" + \
"Pragma: no-cache\r\n" + \
"Cache-Control: no-cache\r\n"


